// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPqGO_gExDIlWy86bxvy-3_qrOyDAxBKw',
    appId: '1:637914400157:web:466e82802b3de0b0d31b74',
    messagingSenderId: '637914400157',
    projectId: 'nr-soporte',
    authDomain: 'nr-soporte.firebaseapp.com',
    storageBucket: 'nr-soporte.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2p6j8djkxk4MLBJ_HkY9qbdTBLC63IQ',
    appId: '1:637914400157:android:6a0db3cb07d303a2d31b74',
    messagingSenderId: '637914400157',
    projectId: 'nr-soporte',
    storageBucket: 'nr-soporte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EROkh1RnOp6wqxBHa291JdTmKuwLNww',
    appId: '1:637914400157:ios:d55e74eee1b3220cd31b74',
    messagingSenderId: '637914400157',
    projectId: 'nr-soporte',
    storageBucket: 'nr-soporte.appspot.com',
    iosClientId: '637914400157-3ucmqs6tk98j1tso78nr8lda39ddgemn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nrSoporteMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9EROkh1RnOp6wqxBHa291JdTmKuwLNww',
    appId: '1:637914400157:ios:216a3636c68af682d31b74',
    messagingSenderId: '637914400157',
    projectId: 'nr-soporte',
    storageBucket: 'nr-soporte.appspot.com',
    iosClientId: '637914400157-9cjctuncbd76mvflo3qst5m32flt732j.apps.googleusercontent.com',
    iosBundleId: 'com.example.nrSoporteMobile.RunnerTests',
  );
}
